// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.1
// source: api/connect.proto

// Canonical wire schema. Generate local Go bindings with make generate.
// Keep the protobuf package and field numbers compatible with existing clients.

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_api_connect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_api_connect_proto_rawDescGZIP(), []int{0}
}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_api_connect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_api_connect_proto_rawDescGZIP(), []int{1}
}

func (x *DataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandRequest) Reset() {
	*x = SendCommandRequest{}
	mi := &file_api_connect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandRequest) ProtoMessage() {}

func (x *SendCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandRequest.ProtoReflect.Descriptor instead.
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return file_api_connect_proto_rawDescGZIP(), []int{2}
}

func (x *SendCommandRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandResponse) Reset() {
	*x = SendCommandResponse{}
	mi := &file_api_connect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandResponse) ProtoMessage() {}

func (x *SendCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandResponse.ProtoReflect.Descriptor instead.
func (*SendCommandResponse) Descriptor() ([]byte, []int) {
	return file_api_connect_proto_rawDescGZIP(), []int{3}
}

func (x *SendCommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_connect_proto protoreflect.FileDescriptor

const file_api_connect_proto_rawDesc = "" +
	"\n" +
	"\x11api/connect.proto\x12\x10transaqConnector\"\r\n" +
	"\vDataRequest\"(\n" +
	"\fDataResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\".\n" +
	"\x12SendCommandRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"/\n" +
	"\x13SendCommandResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc2\x01\n" +
	"\x0eConnectService\x12T\n" +
	"\x11FetchResponseData\x12\x1d.transaqConnector.DataRequest\x1a\x1e.transaqConnector.DataResponse0\x01\x12Z\n" +
	"\vSendCommand\x12$.transaqConnector.SendCommandRequest\x1a%.transaqConnector.SendCommandResponseB\x18Z\x16go-txmlconnector/protob\x06proto3"

var (
	file_api_connect_proto_rawDescOnce sync.Once
	file_api_connect_proto_rawDescData []byte
)

func file_api_connect_proto_rawDescGZIP() []byte {
	file_api_connect_proto_rawDescOnce.Do(func() {
		file_api_connect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_connect_proto_rawDesc), len(file_api_connect_proto_rawDesc)))
	})
	return file_api_connect_proto_rawDescData
}

var file_api_connect_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_connect_proto_goTypes = []any{
	(*DataRequest)(nil),         // 0: transaqConnector.DataRequest
	(*DataResponse)(nil),        // 1: transaqConnector.DataResponse
	(*SendCommandRequest)(nil),  // 2: transaqConnector.SendCommandRequest
	(*SendCommandResponse)(nil), // 3: transaqConnector.SendCommandResponse
}
var file_api_connect_proto_depIdxs = []int32{
	0, // 0: transaqConnector.ConnectService.FetchResponseData:input_type -> transaqConnector.DataRequest
	2, // 1: transaqConnector.ConnectService.SendCommand:input_type -> transaqConnector.SendCommandRequest
	1, // 2: transaqConnector.ConnectService.FetchResponseData:output_type -> transaqConnector.DataResponse
	3, // 3: transaqConnector.ConnectService.SendCommand:output_type -> transaqConnector.SendCommandResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_connect_proto_init() }
func file_api_connect_proto_init() {
	if File_api_connect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_connect_proto_rawDesc), len(file_api_connect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_connect_proto_goTypes,
		DependencyIndexes: file_api_connect_proto_depIdxs,
		MessageInfos:      file_api_connect_proto_msgTypes,
	}.Build()
	File_api_connect_proto = out.File
	file_api_connect_proto_goTypes = nil
	file_api_connect_proto_depIdxs = nil
}
